name: ci-go-sonarcloud

on: 
  pull_request: 
    branches: 
      - develop      

jobs: 
  run-ci: 
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4

      - name: Use Node.js      
        uses: actions/setup-node@v3

        with: 
          node-version: '20.x'

      - name: Install Dependences Of App NodeJS
        run: npm ci

      - name: Build of App
        run: npm run build --if-present

      - name: Test of App NodeJS
        run: npm test --coverprofile=coverage.out
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}